version: '3.8'
services:
  dind-jenkins:
    container_name: dind-jenkins
    build:
      context: .
    image: dind-jenkins:1
    privileged: true
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins:/root/.jenkins
      - ~/.ssh:/root/.ssh  # Пробрасываем SSH-ключи
      - ~/.gitconfig:/root/.gitconfig  # Пробрасываем глобальные настройки Git
    networks:
      - dind-jenkins-network


volumes:
  jenkins:
    name: jenkins
    driver: local


networks:
  dind-jenkins-network:
    driver: bridge